version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: WildDropDev
      POSTGRES_PASSWORD: WildDropDev
      POSTGRES_DB: WildDrop
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
